---
# Adding OSM ATH
- debug: msg="##### 5GTANGO Adding OSM ath {{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"

# ADDING OSM ATH
#- name: "Adding the SP OSM ath"
  #shell: | 
#    /usr/bin/curl -X POST  http://{{ target }}/api/v3/settings/platforms -H 'content-type: application/json' { "name":"osm-athenas", "host":"http://10.30.0.170", "type":"osm", "username":"admin", "password":"admin", "project_name": "admin","vim_account": "OS1", "monitoring_urls":"http://son-vnv-monitor-manager:8000/api/v2/services"}
- name:  "Adding the SP OSM ath"
  uri:
      url: http://{{ target }}:32002/api/v3/settings/platforms
      method: POST
      headers:
          Content-Type: "application/json"      
      body:
         name: osm-athenas
         host: http://10.30.0.170
         type: osm
         username: admin
         password: admin
         project_name: admin
         vim_account: OS1
         service_token: service_token           
         monitoring_urls: http://son-vnv-monitor-manager:8000/api/v2/services           
      status_code: 200,401
      body_format: json

