---
# Running the 5GTANGO Gatekeeper Common (Docker container)
- debug: msg="##### 5GTANGO GTK-COMMON DEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"
- name: run the 5GTANGO GTK-COMMON
  docker_container:
    name: tng-gtk-common
    image: "{{ repository }}/tng-gtk-common:{{ version }}"
    env:
      UNPACKAGER_URL: "{{ unpackager_url }}"
      CATALOGUE_URL: "{{ catalogue_url }}"
      INTERNAL_CALLBACK_URL: "{{ internal_callback_url }}"
      EXTERNAL_CALLBACK_URL: "{{ external_callback_url }}"
    state: started
    recreate: yes
    pull: true
    restart_policy: "always"
    network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - tng-gtk-common
    published_ports:
      - "32003:5000"