---
# Installation Start
- name: Installation Start
  uri:
    url: http://bit.ly/2VCHrnH
    method: GET
    validate_certs: no
    headers:
      User-Agent: "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0"
  ignore_errors: True
  when: target == "localhost"

# Deploying VnV Databases

# deploy postgreSQL database engine
- import_tasks: pgsql.yml
  when: (component == 'database') or
        (component == 'all')

# deploy postgreSQL database engine for monitoring
- import_tasks: pgsql-monitoring.yml
  when: (component == 'database') or
        (component == 'monitoring') or
        (component == 'all')

# deploy mongo
- import_tasks: mongo.yml
  when: (component == 'database') or
        (component == 'all')

# deploy Redis database engine
- import_tasks: redis.yml
  when: (component == 'database') or
        (component == 'all')

# Deploying VnV Components

# deploy tng-vnv-planner
- import_tasks: tng-vnv-planner.yml
  when: (component == 'planner') or
        (component == 'tng-vnv-planner') or
        (component == 'all')

# deploy tng-vnv-curator
- import_tasks: tng-vnv-curator.yml
  when: (component == 'curator') or
        (component == 'tng-vnv-curator') or
        (component == 'all')

# deploy tng-vnv-executor
- import_tasks: tng-vnv-executor.yml
  when: (component == 'executor') or
        (component == 'tng-vnv-executor') or
        (component == 'all')

# deploy tng-cat
- import_tasks: cat.yml
  when: (component == 'catalogues') or
        (component == 'all')

# deploy tng-rep
- import_tasks: rep.yml
  when: (component == 'repositories') or
        (component == 'all')

# deploy tng-gtk-common
- import_tasks: gtk-common.yml
  when: (component == 'gatekeeper') or
        (component == 'gtk-common') or
        (component == 'all')

# deploy tng-gtk-vnv
- import_tasks: gtk-vnv.yml
  when: (component == 'gatekeeper') or
        (component == 'gtk-vnv') or
        (component == 'all')

- import_tasks: gtk-usr.yml
  when: (component == 'gatekeeper') or
        (component == 'gtk-usr') or
        (component == 'all')           

# deploy Security Gateway
- import_tasks: sec-gtw.yml
  when: (component == 'gatekeeper') or
        (component == 'security-gateway') or
        (component == 'all')

# deploy tng-api-gtw
- import_tasks: api-gtw.yml
  when: (component == 'gatekeeper') or
        (component == 'gtk-api-gtw') or
        (component == 'all')

        
# deploy tng-vnv-dsm.yml
- import_tasks: tng-vnv-dsm.yml
  when: (component == 'recommender') or
        (component == 'tng-vnv-dsm') or
        (component == 'all')
        
# deploy tng-sdk-pkg.yml
- import_tasks: tng-sdk-pkg.yml
  when: (component == 'gatekeeper') or
        (component == 'packager') or
        (component == 'all')
        
# deploy Portal
- import_tasks: portal.yml
  when: (component == 'portal') or
        (component == 'all')

# deploy Platform Adapter
- import_tasks: tng-vnv-platform-adapter.yml
  when: (component == 'adapter') or
        (component == 'tng-vnv-platform-adapter') or
        (component == 'all') 

# deploy Monitoring Pushgateway
- import_tasks: pushgw.yml
  when: (component == 'monitoring') or
        (component == 'pushgateway') or
        (component == 'all')

# deploy Monitoring Prometheus
- import_tasks: prometheus.yml
  when: (component == 'monitoring') or
        (component == 'prometheus') or
        (component == 'all')

# deploy Monitoring grafana
- import_tasks: grafana.yml
  when: (component == 'monitoring') or
        (component == 'monitoring-grafana') or
        (component == 'all')

# deploy Monitoring Manager
- import_tasks: monitmgr.yml
  when: (component == 'monitoring') or
        (component == 'monitoring-manager') or
        (component == 'all')

# deploy Monitoring Probe
- import_tasks: probe.yml
  when: (component == 'monitoring') or
        (component == 'monitoring-probe') or
        (component == 'all')     
        
# deploy Analytics Engine
- import_tasks: tng-analytics-engine.yml
  when: (component == 'analytics') or
        (component == 'tng-analytics-engine') or
        (component == 'all') 
        
# deploy R Analytics Server
- import_tasks: tng-analytics-rserver.yml
  when: (component == 'analytics') or
        (component == 'tng-analytics-rserver') or
        (component == 'all') 

# configure qual sp bcn
- import_tasks: add-qual-sp-bcn.yml
  when: (target == 'pre-int-vnv-bcn.5gtango.eu') and
        (component == 'all') 

# configure osm athens
- import_tasks: add-osm-ath.yml
  when: (target == 'pre-int-vnv-bcn.5gtango.eu') and
        (component == 'all')

# Installation Finish
- name: Installation Finish
  uri:
    url: http://bit.ly/2M1yqjp
    method: GET
    validate_certs: no
    headers:
      User-Agent: "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0"
  ignore_errors: True
  when: target == "localhost"
