---
# Running the VnV MONIT MANAGER (Docker container)
- debug: msg="##### VnV MONIT MANAGER DEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"
- name: VnV MONIT MANAGER - running Docker containers
  docker_container:
    name: son-vnv-monitor-manager
    image: "{{ repository }}/son-vnv-monitor-manager:{{ version }}"
    state: started
    recreate: yes
    pull: true
    restart_policy: "always"
    network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - son-vnv-monitor-manager
          - son-monitor-manager
    published_ports:
      - "8000:8000"
      - "8888:8888"
