---
# Running the Sonata PGSQL (Docker container)
- debug: msg="##### SP PGSQL DEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"
- name: deploy a PostgreSQL database server as a Container
  docker_container:
    name: son-postgres   
    image: sonatanfv/son-postgres
    volumes:
      - "/etc/sonata/data/postgres:/var/lib/postgresql/data"
    env:
      POSTGRES_DB: "{{ gtk_db_name }}"
      POSTGRES_USER: "{{ gtk_db_user }}"
      POSTGRES_PASSWORD: "{{ gtk_db_pass }}"
    state: started
    recreate: yes
    pull: true
    restart_policy: "always"
    network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - son-postgres
    published_ports: 5432:5432

- name: Wait until the string "Postgres" is UP
  wait_for: host=0.0.0.0 port=5432 timeout=30 delay=10 state=started


- name: Create planner db
  shell: |
    /usr/bin/docker exec -t son-postgres psql -h localhost -U {{ gtk_db_user }} -d {{ gtk_db_name }} -c "CREATE DATABASE {{ planner_db_name }};"
  ignore_errors: True
