---

- debug: msg="##### Installing python {{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"

- name: Import Docker CE repository gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- name: Gather info
  setup:

- name: Add Docker CE repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Install Docker CE
  apt:
    name: docker-ce
    state: present
    update_cache: yes

- name: Configure insecure registry
  copy: src=docker.service dest=/lib/systemd/system/docker.service

- pause: seconds=20

- name: start Docker engine
  systemd:
    name: docker
    state: started

- pause: seconds=20

- name: Create a docker network
  docker_network:
    name: "tango"
    state: present
  notify:
    - restart docker
