---
# Installing environment tools
# Install Python
- import_tasks: "{{ lookup('env','PWD') }}/roles/prepare-env/tasks/python.yml"

# Install Docker
- import_tasks: "{{ lookup('env','PWD') }}/roles/prepare-env/tasks/docker.yml"

