---
# Running the Sonata INFLUXDB (Docker container)
- debug: msg="##### SP INFLUXDB DEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"
- name: MONIT InfluxDB  - running Docker containers
  docker_container:
    name: son-monitor-influxdb
    image: "{{ repository }}/son-monitor-influxdb:{{ version }}"
    state: started
    recreate: yes
    pull: true
    restart_policy: "always"
    network_mode: bridge
    networks:
    - name: "{{ docker_network_name }}"
      aliases:
        - son-monitor-influxdb
        - influxdb
        - influx
    published_ports: 8086:8086

