---
# Running the Sonata GTK-KPI (Docker container)
- debug: msg="##### SP GTK-KPI DEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"
- name: GATEKEEPER KEY PERFORMANCE INDICATORS (GTKKPI) (Docker container)
  docker_container:
    name: son-gtkkpi
    image: "{{ repository }}/son-gtkkpi:{{ version }}"
    state: started
    recreate: yes
    pull: true
    restart_policy: "always"
    env:
      PUSHGATEWAY_HOST: "pushgateway"
      PUSHGATEWAY_PORT: 9091
      PROMETHEUS_PORT: 9090
      RACK_ENV: integration
    network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - son-gtkkpi
    published_ports: "5400:5400"
