---
# Running the Sonata GK RATE LIMITER (Docker container)
- debug: msg="##### SP GTK-RATE-LIMITER DEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"
- name: GATEKEEPER RATE LIMITER (GTKRLT) (Docker container)
  docker_container:
    name: son-gtkrlt
    image: "{{ repository }}/son-gtkrlt:{{ version }}"
    env:
      REDIS_URL=redis://son-redis:6379
    state: started
    recreate: yes
    pull: true
    restart_policy: "always"
    network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - son-gtkrlt
    exposed_ports: 5150
    published_ports: "5150:5150"
