---
# Running the Sonata MONIT SNMP MANAGER (Docker container)
- debug: msg="##### SP MONIT SNMP_MNG DEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"
- name: MONIT SNMP_MNG - running Docker containers
  docker_container:
    name: son-monitor-snmpmng
    image: "{{ repository }}/son-monitor-snmpmng:{{ version }}"
    restart_policy: "always"
    state: started
    recreate: yes
    pull: true
    env:
      POSTGS_PORT: "5433"
      POSTGS_HOST: "son-monitor-postgres"
      DB_USER_NAME: "monitoringuser"
      DB_USER_PASS: "sonata"
      PROM_SRV: "[\"son-monitor-pushgateway:9091\"]"
    network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - son-monitor-snmpmng
    

