---
# Running the 5GTango POLICY MANAGER (Docker container)
- debug: msg="##### SP POLICY MANAGER DEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"
- name: POLICY MANAGER - running Docker containers
  docker_container:
    name: tng-policy-mngr
    image: "{{ repository }}/tng-policy-mngr:{{ version }}"
    state: started
    recreate: yes
    pull: true
    restart_policy: "always"
    env:
      MONGO_DB: "son-mongo"
      HOST_BROKER: "son-broker"
      CATALOGUE: "tng-cat:4011"
      MONITORING_MANAGER: "son-monitor-manager:8000"
    network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - tng-policy-mngr
    published_ports:
      - "8081:8081"
