---
# Running the Sonata SP GTK-USER-MGMT Docker Image
- debug: msg="##### SP GTK-USER-MGMT DEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"

- name: GATEKEEPER USER MANAGEMENT (GTKUSR) (Docker container)
  docker_container:
    name: son-gtkusr
    image: "{{ repository }}/son-gtkusr:{{ version }}"
    state: started
    recreate: yes
    pull: true
    env:
      KEYCLOAK_ADDRESS: son-keycloak
      KEYCLOAK_PORT: 5601
      KEYCLOAK_PATH: auth
      SONATA_REALM: sonata
      CLIENT_NAME: adapter 
    network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - son-gtkusr
    published_ports: "5600:5600"
    restart_policy: "always"

- name: Wait until the string "GtkUserMgmt" is UP
  wait_for: host=0.0.0.0 port=5600 timeout=30 delay=10 state=started

