---
# Running the Sonata Infrastructure Abstractor VIM Ovs Wrapper (Docker container)
- debug: msg="##### SP Infrastructure Abstractor VIM Ovs Wrapper DEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"
- name: deploying Infrastructure Abstractor VIM Ovs Wrapper (Docker container)
  docker_container:
    name: vim-wrapper-ovs
    image: "{{ repository }}/vim-wrapper-ovs:{{ version }}"
    restart_policy: "always"
    state: started
    recreate: yes
    pull: true
    env:
      broker_host: "son-broker"
      broker_uri: "amqp://guest:guest@son-broker:5672/%2F"
      repo_host: "son-postgres"
      repo_port: "5432"
      repo_user: "{{ ia_repo_user }}"
      repo_pass: "{{ ia_repo_pass }}"
    network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        links:
          - son-broker
