---
# Running the Sonata Infrastructure Abstractor WIM Adaptor (Docker container)
- debug: msg="##### SP Infrastructure Abstractor WIM Adaptor DEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"
- name: deploying Infrastructure Abstractor WIM Adaptor (Docker container)
  docker_container:
    name: wim-adaptor
    image: "{{ repository }}/wim-adaptor:{{ version }}"
    restart_policy: "always"
    state: started
    recreate: yes
    pull: true
    env:
      broker_host: "son-broker"
      broker_uri: "amqp://guest:guest@son-broker:5672/%2F"
      repo_host: "son-postgres"
      repo_port: "5432"
      repo_user: "{{ ia_repo_user }}"
      repo_pass: "{{ ia_repo_pass }}"
      network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - wim-adaptor

